# Generated by Django 5.2.3 on 2025-07-21 16:51

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('altered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('altered_at', models.DateTimeField(auto_now=True)),
                ('cardapio', models.ManyToManyField(to='japapou.cardapio')),
            ],
        ),
    ]
