# Generated by Django 5.2.3 on 2025-07-21 16:59

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0002_cardapio_prato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='prato',
            name='cardapio',
        ),
        migrations.AddField(
            model_name='prato',
            name='menu',
            field=models.ManyToManyField(to='japapou.menu'),
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
    ]
