# Generated by Django 5.2.3 on 2025-07-21 17:02

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0003_menu_remove_prato_cardapio_prato_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='pratos',
            field=models.ManyToManyField(to='japapou.prato'),
        ),
    ]
