# Generated by Django 5.2.3 on 2025-07-21 17:25

import django.db.models.deletion  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0004_remove_prato_menu_menu_pratos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('altered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='pratos',
        ),
        migrations.AddField(
            model_name='menu',
            name='cardapio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='japapou.cardapio'),
        ),
        migrations.AddField(
            model_name='menu',
            name='pratos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='japapou.prato'),
        ),
    ]
