# Generated by Django 5.2.3 on 2025-07-21 17:56

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0005_cardapio_remove_menu_pratos_menu_cardapio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='pratos',
        ),
        migrations.AddField(
            model_name='menu',
            name='pratos',
            field=models.ManyToManyField(null=True, to='japapou.prato'),
        ),
    ]
