# Generated by Django 5.2.3 on 2025-07-21 18:16

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("japapou", "0006_remove_menu_pratos_menu_pratos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardapio",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Cardápio",
                "verbose_name_plural": "Cardápios",
            },
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "Menu", "verbose_name_plural": "Menus"},
        ),
        migrations.AlterModelOptions(
            name="prato",
            options={
                "ordering": ["name"],
                "verbose_name": "Prato",
                "verbose_name_plural": "Pratos",
            },
        ),
        migrations.AlterField(
            model_name="menu",
            name="pratos",
            field=models.ManyToManyField(blank=True, null=True, to="japapou.prato"),
        ),
    ]
