# Generated by Django 5.2.3 on 2025-07-22 16:43

import django.db.models.deletion  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0007_alter_cardapio_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('altered_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cardapio',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='pratos',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='data_ini',
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='japapou.menu')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='plates',
            field=models.ManyToManyField(blank=True, null=True, to='japapou.plate'),
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
        migrations.DeleteModel(
            name='Prato',
        ),
    ]
