# Generated by Django 5.2.3 on 2025-07-22 16:58

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0008_plate_remove_menu_cardapio_remove_menu_pratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Menu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='plates',
            field=models.ManyToManyField(blank=True, to='japapou.plate'),
        ),
    ]
