# Generated by Django 5.2.3 on 2025-07-22 18:25

import django.db.models.deletion  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("japapou", "0009_menu_name_alter_menu_plates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="menu",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="japapou.menu",
            ),
            preserve_default=False,
        ),
    ]
